# Generated by Django 6.0.3 on 2026-03-24 01:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_publicacionclase_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='gym.miembro')),
            ],
        ),
    ]
