# Generated by Django 6.0.3 on 2026-03-24 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_tokenacceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(limit_choices_to={'rol__nombre': 'ENTRENADOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='gym.miembro')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='gym.curso'),
        ),
    ]
