# Generated by Codex on 2026-03-24
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0004_curso_clase_curso"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacionclase",
            name="archivo_1",
            field=models.FileField(blank=True, null=True, upload_to="clases/archivos/"),
        ),
        migrations.AddField(
            model_name="publicacionclase",
            name="archivo_2",
            field=models.FileField(blank=True, null=True, upload_to="clases/archivos/"),
        ),
        migrations.AddField(
            model_name="publicacionclase",
            name="archivo_3",
            field=models.FileField(blank=True, null=True, upload_to="clases/archivos/"),
        ),
    ]
